### ISSUE TITLE
Animation not working plus a feature request

### ISSUE THREAD

**Issue by antgustech** [Sese-Schneider/ha-energy-overview-card#15]
```
`type: custom:energy-overview-card
entities:
  - power: sensor.electricity_meter_power_consumption_phase_l1
    current: sensor.electricity_meter_current_phase_l1
    voltage: sensor.electricity_meter_voltage_phase_l1
    animation:
      power: 100
      min_duration: 2
      max_duration: 5
    label_leading: P
    label_trailing: L1
    icon_leading: mdi:transmission-tower
    icon_trailing: mdi:home-lightning-bolt
  - power: sensor.electricity_meter_power_consumption_phase_l2
    current: sensor.electricity_meter_current_phase_l2
    voltage: sensor.electricity_meter_voltage_phase_l2
    animation:
      power: 100
      min_duration: 2
      max_duration: 5
    label_leading: P
    label_trailing: L2
    icon_leading: mdi:transmission-tower
    icon_trailing: mdi:home-lightning-bolt
  - power: sensor.electricity_meter_power_consumption_phase_l3
    current: sensor.electricity_meter_current_phase_l3
    voltage: sensor.electricity_meter_voltage_phase_l3
    animation:
      power: 100
      min_duration: 2
      max_duration: 5
    label_leading: P
    label_trailing: L3
    icon_leading: mdi:transmission-tower
    icon_trailing: mdi:home-lightning-bolt
animation:
  power: 1000
  min_duration: 1
  max_duration: 10
`
```

With this config, animation only plays over 1000w and not over a 100.

Also a feature request; would be nice to add a 4 bar or some sort of summary of the totalt power etc.
