### ISSUE TITLE
Power consumption/production in one animation

### ISSUE THREAD

**Issue by marcelvandorp** [Sese-Schneider/ha-energy-overview-card#21]
Hi,
I have a feature request:

I see that negative values will show the animation from right to left (as expected). My DSMR has two sensors per line: Power Consumption and Power Production. Both are positive values. But When I have Production, I do not have Consumption and vice versa

Is there a way to display the results of the calculation: Consumption-Production? That is: with Consumption this is a positive value, and with Production this is a negative value. This way the animation shows exactly the flow of energy as it occurs.

I tried a template, but this isn't recognized (or I do something wrong).

This is a simple test config that works:

```
type: custom:energy-overview-card
entities:
  - power: input_number.schuiver
    label_leading: P
    label_trailing: L1
    icon_leading: mdi:transmission-tower
    icon_trailing: mdi:home-lightning-bolt
    color: '#488fc2'
```
But if I change the power line to use a template, like this:

`  - power: "{{ states('input_number.schuiver') }}"`

It doesn't show anything. This line only uses a template to retrieve the value, no calculations are done (yet)

I am aware I can solve this with a template sensor, but I believe a solution in this card is the cleaner solution.
