### ISSUE TITLE
Which entities to use?

### ISSUE THREAD

**Issue by PrzemekSkw** [Sese-Schneider/ha-energy-overview-card#34]
Hello, I want to add energy card to my Unraid server monitoring dashboard but I got only 3 entities that are different named:
![image](https://github.com/user-attachments/assets/b2b865ba-a53c-4f9a-9fbf-9bea5c1be114)

Can I use ha-energy-overview-card in my case?
Regards.

**Comment by Sese-Schneider** [comment]
Hi @PrzemekSkw , you should be able to use `sensor.unraid_ups_current_power` for a basic card.

```yaml
type: custom:energy-overview-card
entities:
  - power: sensor.unraid_ups_current_power
```
