### ISSUE TITLE
can't find the card

### ISSUE THREAD

**Issue by nicoolaro** [Sese-Schneider/ha-energy-overview-card#4]
Can someone help me with examples of the card?
Is this a manual card ? because i am not seeing it in card even though integration is there.

**Comment by Sese-Schneider** [comment]
@nicoolaro this is an example configuration with the Shelly 3EM

```yaml
type: custom:energy-overview-card
a_current: sensor.shellyem3_yourid_channel_a_current
b_current: sensor.shellyem3_yourid_channel_b_current
c_current: sensor.shellyem3_yourid_channel_c_current
a_voltage: sensor.shellyem3_yourid_channel_a_voltage
b_voltage: sensor.shellyem3_yourid_channel_b_voltage
c_voltage: sensor.shellyem3_yourid_channel_c_voltage
a_power: sensor.shellyem3_yourid_channel_a_power
b_power: sensor.shellyem3_yourid_channel_b_power
c_power: sensor.shellyem3_yourid_channel_c_power
a_power_factor: sensor.shellyem3_yourid_channel_a_power_factor
b_power_factor: sensor.shellyem3_yourid_channel_b_power_factor
c_power_factor: sensor.shellyem3_yourid_channel_c_power_factor
```
