### ISSUE TITLE
Dot directions not changing when the power value is negative

### ISSUE THREAD

**Issue by Grandma-Betty** [Sese-Schneider/ha-energy-overview-card#6]
Hey mate, I'm the dude from Reddit with the changing dot direction issue ;-)
To add more information about the issue: I never installed your add-on outside of HACS.
Here is my config:

```
type: custom:energy-overview-card
a_current: sensor.shelly3em01_channel_a_current
b_current: sensor.shelly3em01_channel_b_current
c_current: sensor.shelly3em01_channel_c_current
a_voltage: sensor.shelly3em01_channel_a_voltage
b_voltage: sensor.shelly3em01_channel_b_voltage
c_voltage: sensor.shelly3em01_channel_c_voltage
a_power: sensor.shelly3em01_channel_a_power
b_power: sensor.shelly3em01_channel_b_power
c_power: sensor.shelly3em01_channel_c_power
a_power_factor: sensor.shelly3em01_channel_a_power_factor
b_power_factor: sensor.shelly3em01_channel_b_power_factor
c_power_factor: sensor.shelly3em01_channel_c_power_factor
```

![Unbenannt](https://user-images.githubusercontent.com/48346793/215782120-0d38a8f9-eb5a-42d4-9d7b-0d4114b0d283.PNG)

Thanks!

**Comment by Sese-Schneider** [comment]
Hi @Grandma-Betty

Your config looks invalid for the most recent release.
Please ensure manually you have the correct version `2.0.1` installed!
![image](https://user-images.githubusercontent.com/14337484/215794612-65f3d8a3-39d7-4b89-b536-f2f88297d66f.png)

⚠️ There are breaking changes with the new config according to the [release notes](https://github.com/Sese-Schneider/ha-energy-overview-card/releases)
Your config would need to change to something like this after updating:

```yaml
type: custom:energy-overview-card
entities:
  - power: sensor.shelly3em01_channel_a_power
    current: sensor.shelly3em01_channel_a_current
    voltage: sensor.shelly3em01_channel_a_voltage
    power_factor: sensor.shelly3em01_channel_a_power_factor
    label_trailing: 'A'
    icon_leading: 'mdi:transmission-tower'
    icon_trailing: 'mdi:home-lightning-bolt'
    color: '#488fc2'
  - power: sensor.shelly3em01_channel_b_power
    current: sensor.shelly3em01_channel_b_current
    voltage: sensor.shelly3em01_channel_b_voltage
    power_factor: sensor.shelly3em01_channel_b_power_factor
    label_trailing: 'B'
    color: '#7dbff5'
  - power: sensor.shelly3em01_channel_c_power
    current: sensor.shelly3em01_channel_c_current
    voltage: sensor.shelly3em01_channel_c_voltage
    power_factor: sensor.shelly3em01_channel_c_power_factor
    label_trailing: 'C'
    color: '#b1f2ff'
```
