### ISSUE TITLE
Power factor of Phase A not available

### ISSUE THREAD

**Issue by Grandma-Betty** [Sese-Schneider/ha-energy-overview-card#8]
The power factor of Phase A is not available somehow, Phase B and Phase C seem to be ok.
Could it be because of negative values?
I'm on the latest version 2.1.0.
Thanks!

![Unbenannt](https://user-images.githubusercontent.com/48346793/219587714-8e4e1431-b150-45ee-a8ea-75c52155d0c6.PNG)

EDIT:

```
      - type: custom:energy-overview-card
        entities:
          - power: sensor.shelly3em01_channel_a_power
            current: sensor.shelly3em01_channel_a_current
            voltage: sensor.shelly3em01_channel_a_voltage
            power_factor: sensor.shelly3em01_channel_a_power_factor
            label_trailing: A
            icon_leading: mdi:transmission-tower
            icon_trailing: mdi:home-lightning-bolt
            color: '#488fc2'
          - power: sensor.shelly3em01_channel_b_power
            current: sensor.shelly3em01_channel_b_current
            voltage: sensor.shelly3em01_channel_b_voltage
            power_factor: sensor.shelly3em01_channel_b_power_factor
            label_trailing: B
            color: '#7dbff5'
          - power: sensor.shelly3em01_channel_c_power
            current: sensor.shelly3em01_channel_c_current
            voltage: sensor.shelly3em01_channel_c_voltage
            power_factor: sensor.shelly3em01_channel_c_power_factor
            label_trailing: C
            color: '#b1f2ff'
```
